### ISSUE TITLE
Firebase Integration

### ISSUE THREAD

**Issue by GemiDroid** [greensopinion/gradle-android-eclipse#11]
Hello,
I couldn't integrate firebase in my gradle file.
And face some issues in compiling...could you help me with example ?
Appreciate your reply..

**Comment by greensopinion** [comment]
Hey @GemiDroid thanks for your comment.  It's not clear from the information that you provided what your problem is or how it's related to this project.  I'm going to close as unrelated, but if you can show that this somehow an issue with this Gradle plug-in, would consider reopening.
