### ISSUE TITLE
The type R/BuildConfig is already defined

### ISSUE THREAD

**Issue by schildbach** [greensopinion/gradle-android-eclipse#16]
After running `gradle eclipse` and applying the workarounds from #14 and #15, I've got two remaining build errors:

```
The type BuildConfig is already defined.
The type R is already defined.
```

This is because andmore (0.5.1) creates these files into the `gen` folder, and this cannot be disabled afaik. And gradle-android-eclipse generates another set into `build/generated/source/r/debug` and `build/generated/source/buildConfig/debug` respectively.

I suggest gradle-android-eclipse should not create the own project's `R.java` and `BuildConfig.java` files, since andmore already takes care of this.

**Comment by schildbach** [comment]
Workaround: I can delete the two files manually (e.g. from within Eclipse) and the problem is gone.

**Comment by greensopinion** [comment]
gradle-android-eclipse isn't generating any java files directly, that must be coming from somewhere else (e.g. https://docs.gradle.org/current/userguide/eclipse_plugin.html, which this plug-in extends.) I recommend driving changes into that project instead.

**Comment by schildbach** [comment]
Then the documentation is wrong. According to https://github.com/greensopinion/gradle-android-eclipse#what-it-does the files are generated in fact by gradle-android-eclipse.

**Comment by schildbach** [comment]
And actually I don't know why Android-ony artifacts should be created by the generic Eclipse plugin.
