### ISSUE TITLE
Usage with Gradle 5

### ISSUE THREAD

**Issue by Monstratus** [greensopinion/gradle-android-eclipse#18]
Hello!
That plugin is very useful. Thanks for u work.
Do you plan to optimize it for gradle 5?
I want to set up a project under eclipse with androidx, and am looking for different ways to do this.
Before i used gradle 4 and Gradle EnIDE (nodeclipse) and everything was fine. But google has implemented databinding and androidx in android.tools.build 3.4. This has become a problem for me.
Maybe you know other ways to solve this problem (except Android Studio)?
I would be very grateful for any advice.

**Comment by greensopinion** [comment]
Hi Monstratus, no plans to do anything here. Feel free to fork & change to suit your needs.
