### ISSUE TITLE
 src/main/java is hardcoded into .classpath

### ISSUE THREAD

**Issue by pvagner** [greensopinion/gradle-android-eclipse#3]
I am trying to use this plugin to generate eclipse project for android app however my project has a different directory structure. I do have all the source files inside the src directory with no main/java inside.
I do have overridden main.java source set in the build.gradle script, my src path is incuded in the resulting claspath however there's always redundant src/main/java added to the classpath.
It would be nice if this plugin would verify if the hardcoded path is valid before adding it or if it provided enough configuration.

Edit: gradle eclipse plugin is looking at top level sourceSets. Thus I can trick gradle eclipse plugin to add my non-standard path by adding it to the top level main.java source set.
When handling android projects sourceSets is not a top level thing but it's nested inside the android {} block. So adding both sourceSets one at the top level and the other one within the android block is somewhat redundant I think. android specific sourceSet has some more types besides src and resources, so that's another argument why to prefer android specific sourceSets configuration for android projects.
So it would be natural to take the java.srcDirs from each source set defined under android.sourceSets instead of hardcoding src/main/java . 
Is this doable?

Until this is not properly addressed here is a dirty way on how I got it to work...
		file.beforeMerged { classpath ->
			classpath.entries.add(new org.gradle.plugins.ide.eclipse.model.SourceFolder("src", "bin"))
		}
		file.whenMerged { classpath ->
			classpath.entries.removeAll { it.path.endsWith("src/main/java") }
		}

**Comment by greensopinion** [comment]
Thanks for raising the issue, and great to see that there's a workaround!  

You're right of course, this plug-in relies on projects following convention when it comes to layout.
To help me understand your use-case, what is the reasoning for having a non-standard directory structure?

**Comment by pvagner** [comment]
Well, I would say my use case is not very special.
We are using eclipse and android ADT to build the app. The release builds are still being made with android-sdk 23 targetting API 21 formally although there might be a few API 22 calls.
I am trying to move out of Android ADT for eclipse as I am having issues with it each time I'm installing android SDK update or android platform update and similar.
Just for the convenience I like to have up to date tools and SDKs installed so I can also build other apps occassionally.
So as a first step I have added gradle based build configuration to our project which will be used side by side with the original android ADT build configuration. If my team mate developer will also find this gradle based build config usefull we might consider switching to it in the future.
If nothing else then we are at least partially prepared for using up to date SDK and build tools.
So the project layout is oldskool with flat folders
src
res
assets

**Comment by greensopinion** [comment]
You probably already know, but just in case: ADT is no longer officially supported.  See http://android-developers.blogspot.com/2016/11/support-ended-for-eclipse-android.html for details.

This plug-in is intended for Gradle projects that use a standard layout (as produced by Android Studio).  I'm sorry but your request is beyond the scope of this project.  

I'm glad that you've got a workaround.  You may want to consider moving to a supported tool chain.

**Comment by mortalis13** [comment]
Another workaround:

    eclipse {
      classpath {
        file.whenMerged {
          classpath -> classpath.entries.each {
            if (it.kind == "src" && it.path.equals("src/main/java")) it.path = "src"
          }
        }
      }
    }
